name: Changesets
on:
  push:
    branches:
      - v-next
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  changesetcheck:
    runs-on: ubuntu-latest
    outputs:
      CHANGESETS: ${{ steps.changesetcheck.outputs.CHANGESETS }}
    steps:
      - name: checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - name: Install
        run: pnpm install --no-frozen-lockfile
      - name: changesetcheck
        run: |
          pnpm changeset status --output=changes.json
          cat changes.json | grep "\"releases\": \[\],"
          if [ $? -eq 0 ]; then
            echo "No changeset found"
            echo "CHANGESETS=notfound" >> "$GITHUB_OUTPUT"
          else
            echo "Changesets found"
            echo "CHANGESETS=found" >> "$GITHUB_OUTPUT"
          fi

  release:
    runs-on: ubuntu-latest
    needs: changesetcheck
    steps:
      - name: Release check
        env:
          CHANGESETS: ${{needs.changesetcheck.outputs.CHANGESETS}}
        run: echo "$CHANGESETS"
